FactoryBot.define do
  factory :rakuten_order do
    order_id { "#{Faker::Number.number(digits: 6)}-#{Faker::Date.backward.strftime('%Y%m%d')}-#{Faker::Number.number(digits: 10)}" }
    order_time { FFaker::Time.between(from: 2.days.ago, to: Time.current, format: :default) }
    arrival_date { FFaker::Date.forward(1) }
    ship_dates { [FFaker::Date.forward(0).to_s] }
    status { 100 } # Assuming status is a static value in this case
    data do
      { "orderNumber" => order_id,
        "orderProgress" => 100,
        "subStatusId" => 15822,
        "subStatusName" => "注文確認待ち",
        "orderDatetime" => "2023-12-18T16:03:26+0900",
        "shopOrderCfmDatetime" => nil,
        "orderFixDatetime" => nil,
        "shippingInstDatetime" => nil,
        "shippingCmplRptDatetime" => nil,
        "cancelDueDate" => "2024-01-01",
        "deliveryDate" => "2023-12-20",
        "shippingTerm" => 1921,
        "remarks" => "[配送日時指定:]\n\n19:00-21:00\n\n[メッセージ添付希望・他ご意見、ご要望がありましたらこちらまで:]\n納期１&#12316;２日となってるので12/24に欲しいので日付指定はしませんでした。届きますか？\n",
        "giftCheckFlag" => 0,
        "severalSenderFlag" => 0,
        "equalSenderFlag" => 0,
        "isolatedIslandFlag" => 0,
        "rakutenMemberFlag" => 1,
        "carrierCode" => 12,
        "emailCarrierCode" => 3,
        "orderType" => 1,
        "reserveNumber" => nil,
        "reserveDeliveryCount" => nil,
        "cautionDisplayType" => 0,
        "cautionDisplayDetailType" => nil,
        "rakutenConfirmFlag" => 0,
        "goodsPrice" => 7600,
        "goodsTax" => 0,
        "postagePrice" => 0,
        "deliveryPrice" => 0,
        "paymentCharge" => 0,
        "paymentChargeTaxRate" => 0.1,
        "totalPrice" => 7600,
        "requestPrice" => 7600,
        "couponAllTotalPrice" => 0,
        "couponShopPrice" => 0,
        "couponOtherPrice" => 0,
        "additionalFeeOccurAmountToUser" => 0,
        "additionalFeeOccurAmountToShop" => 0,
        "asurakuFlag" => 0,
        "drugFlag" => 0,
        "dealFlag" => 0,
        "membershipType" => 0,
        "memo" => "3 備考あり",
        "operator" => nil,
        "mailPlugSentence" => nil,
        "modifyFlag" => 0,
        "receiptIssueCount" => 0,
        "receiptIssueHistoryList" => [],
        "OrdererModel" =>
  { "zipCode1" => FFaker::Number.number(digits: 3),
    "zipCode2" => FFaker::Number.number(digits: 4),
    "prefecture" => FFaker::Address.state,
    "city" => FFaker::Address.city,
    "subAddress" => "#{rand(1..30)}-#{rand(1..30)}",
    "familyName" => FFaker::NameJA.last_name,
    "firstName" => FFaker::NameJA.first_name,
    "familyNameKana" => "フナビキ",
    "firstNameKana" => "コウジ",
    "phoneNumber1" => FFaker::Number.number(digits: 3),
    "phoneNumber2" => FFaker::Number.number(digits: 4),
    "phoneNumber3" => FFaker::Number.number(digits: 4),
    "emailAddress" => 'email@fake.com',
    "sex" => "女",
    "birthYear" => 1910,
    "birthMonth" => 1,
    "birthDay" => 1 },
        "SettlementModel" =>
  { "settlementMethodCode" => 1,
    "settlementMethod" => "クレジットカード",
    "rpaySettlementFlag" => 1,
    "cardName" => "MASTER",
    "cardNumber" => "XXXX-XXXX-XXXX-0000",
    "cardOwner" => "FUNABIKI KOUJI",
    "cardYm" => "2050-01",
    "cardPayType" => 0,
    "cardInstallmentDesc" => nil },
        "DeliveryModel" => { "deliveryName" => "クール便", "deliveryClass" => 2 },
        "PointModel" => { "usedPoint" => 0 },
        "WrappingModel1" => nil,
        "WrappingModel2" => nil,
        "PackageModelList" =>
  [{ "basketId" => 2117568357,
     "postagePrice" => 0,
     "postageTaxRate" => 0.1,
     "deliveryPrice" => 0,
     "deliveryTaxRate" => 0.1,
     "goodsTax" => 0,
     "goodsPrice" => 7600,
     "totalPrice" => 7600,
     "noshi" => nil,
     "defaultDeliveryCompanyCode" => "1001",
     "packageDeleteFlag" => 0,
     "SenderModel" =>
     { "zipCode1" => "111",
       "zipCode2" => "1234",
       "prefecture" => "東京都",
       "city" => "港区",
       "subAddress" => "#{rand(1..30)}-#{rand(1..30)}",
       "familyName" => FFaker::NameJA..last_name,
       "firstName" => FFaker::NameJA..first_name,
       "familyNameKana" => "フナビキ",
       "firstNameKana" => "コウジ",
       "phoneNumber1" => FFaker::Number.number(digits: 3),
       "phoneNumber2" => FFaker::Number.number(digits: 4),
       "phoneNumber3" => FFaker::Number.number(digits: 4),
       "isolatedIslandFlag" => 0 },
     "ItemModelList" =>
     [{ "itemDetailId" => 2117568357,
        "itemName" => "坂越産 生牡蠣むき身500g×3",
        "itemId" => 10000018,
        "itemNumber" => nil,
        "manageNumber" => "10000018",
        "price" => 7600,
        "units" => 1,
        "includePostageFlag" => 0,
        "includeTaxFlag" => 1,
        "includeCashOnDeliveryPostageFlag" => 0,
        "selectedChoice" =>
        "佃煮:なし\nOyster38:なし\n年内お届け最終は１２／２７です。また１２／２８〜１／８はお届け日の指定はできません。:了承した\n最短お届けは【希望日指定なし】でご注文ください。また注文後、お届け日の変更はできません。:了承した。\n年末は配送件数増加の上、交通渋滞や天候悪化でお届け遅延が生じやすくなります。お届け日時は余裕をもってご指定下さい。:確認した",
        "pointRate" => 1,
        "pointType" => 0,
        "inventoryType" => 2,
        "delvdateInfo" => "1〜2日でお届けできます。",
        "restoreInventoryFlag" => 0,
        "dealFlag" => 0,
        "drugFlag" => 0,
        "deleteItemFlag" => 0,
        "taxRate" => 0.08,
        "priceTaxIncl" => 7600,
        "isSingleItemShipping" => 0,
        "SkuModelList" => [{ "variantId" => "r-mukimi3", "merchantDefinedSkuId" => "r-mukimi03", "skuInfo" => "パック数:3パック" }] }],
     "ShippingModelList" => [{ "shippingDetailId" => 2598761447, "shippingNumber" => nil, "deliveryCompany" => "1001", "deliveryCompanyName" => "ヤマト運輸", "shippingDate" => "2023-12-19" }],
     "DeliveryCvsModel" => nil }],
        "CouponModelList" => nil,
        "ChangeReasonModelList" => [],
        "TaxSummaryModelList" => [{ "taxRate" => 0.08, "reqPrice" => 7600, "reqPriceTax" => 562, "totalPrice" => 7600, "paymentCharge" => 0, "couponPrice" => 0, "point" => 0 }],
        "DueDateModelList" => [] }
    end
    created_at { FFakerTime.between(from: 2.days.ago, to: Time.current, format: :default) }
    updated_at { created_at }
    stat_id { nil }
  end
end
